"""
Ask Your Data - 
What this script does :
1. Connects to MySQL database.
2. Sends our question + table info to Gemini (the AI).
3. Gemini replies with a SQL query.
4. We run that query on the database.
5. We print the result.

No Streamlit, no test file, no fancy safety checks yet.
Just the core idea working end to end, so lets understand every step.
"""

import os
import re

import google.generativeai as genai
import mysql.connector
from dotenv import load_dotenv

# Step 0: Load secret keys from the .env file
load_dotenv() 
print("DB_USER loaded as:", os.getenv("DB_USER"))
print("DB_HOST loaded as:", os.getenv("DB_HOST"))
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
model = genai.GenerativeModel("gemini-3.6-flash")


# ----question we want to ask ----
question = "Delete all restaurants with rating below 2"


# -- table name from Workbench ----
TABLE_NAME = "zomato_restaurants"


# Keywords that should never appear in a query we run.
# This is a second layer of protection, on top of the database
# user already being read-only.
FORBIDDEN_KEYWORDS = ["insert", "update", "delete", "drop", "alter", "truncate", "create", "grant", "revoke"]
 
 
def check_sql_is_safe(sql):
    """
    Checks the SQL text before running it:
    1. It starts with SELECT (or WITH).
    2. It isn't secretly more than one statement.
    3. It doesn't contain any dangerous keywords.
    Returns (True, "OK") if safe, or (False, reason) if not.
    """
    cleaned = sql.strip().rstrip(";")
 
    if not cleaned.lower().startswith(("select", "with")):
        return False, "Query does not start with SELECT."
 
    if ";" in cleaned:
        return False, "Query contains more than one statement."
 
    for word in FORBIDDEN_KEYWORDS:
        if re.search(rf"\b{word}\b", cleaned, re.IGNORECASE):
            return False, f"Query contains a blocked keyword: {word}"
 
    return True, "OK"




# Connect to MySQL
print("Connecting to database...")
conn = mysql.connector.connect(
    host=os.getenv("DB_HOST", "localhost"),
    user=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD"),
    database=os.getenv("DB_NAME"),
)
cursor = conn.cursor()


# Get the table structure, so the AI knows what columns exist
print("Reading table structure...")
cursor.execute(f"DESCRIBE {TABLE_NAME}")
columns_info = cursor.fetchall()

schema_text = f"Table: {TABLE_NAME}\nColumns:\n"
for col in columns_info:
    schema_text += f"- {col[0]} ({col[1]})\n"

print("\n--- Schema sent to AI ---")
print(schema_text)


# Ask Gemini to write the SQL query
print("Asking AI to write SQL...")
prompt = f"""You are a MySQL expert.
{schema_text}

Write ONE MySQL SELECT query that answers this question: "{question}"
Return only the SQL query. No explanation. No markdown formatting."""

response = model.generate_content(prompt)
sql_query = response.text.strip()
sql_query = sql_query.replace("```sql", "").replace("```", "").strip()

print("\n--- SQL generated by AI ---")
print(sql_query)



# Step 4: Check the SQL is safe before running it
is_safe, reason = check_sql_is_safe(sql_query)
if not is_safe:
    print(f"\nBLOCKED - not running this query. Reason: {reason}")
    cursor.close()
    conn.close()
    exit()
 
print("\nSafety check passed. Proceeding to run the query.")




# Run that SQL query
print("\nRunning the query...")
cursor.execute(sql_query)
rows = cursor.fetchall()
column_names = [desc[0] for desc in cursor.description]


# Print the result
print("\n--- Result ---")
print(column_names)
for row in rows:
    print(row)


# Clean up
cursor.close()
conn.close()



